Repository alfasoftware/morf, pull requests merged in 2023-05, with the labels that each got.

#248 Add H2 override for row number function
  morf-h2/src/main/java/org/alfasoftware/morf/jdbc/h2/H2Dialect.java
  morf-h2/src/test/java/org/alfasoftware/morf/jdbc/h2/TestH2Dialect.java
Labels: bug, h2-only

#246 SqlDialect.fetchSizeForBulkSelects update
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/AbstractConnectionResources.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/ConnectionResources.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/ConnectionResourcesBean.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/DatabaseDataSetProducer.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/ResultSetIterator.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlDialect.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlScriptExecutor.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/SqlScriptExecutorProvider.java
  morf-core/src/test/java/org/alfasoftware/morf/jdbc/TestConnectionResourcesBean.java
  morf-core/src/test/java/org/alfasoftware/morf/jdbc/TestResultSetIterator.java
  morf-core/src/test/java/org/alfasoftware/morf/jdbc/TestSqlScriptExecutor.java
  morf-integration-test/src/test/java/org/alfasoftware/morf/jdbc/TestMergingDatabaseDataSetConsumer.java
  morf-oracle/src/main/java/org/alfasoftware/morf/jdbc/oracle/OracleDialect.java
Labels: bug, incomplete, performance

#249 Adding id column for upgrade status table
  morf-core/src/main/java/org/alfasoftware/morf/upgrade/UpgradeStatusTableServiceImpl.java
  morf-core/src/test/java/org/alfasoftware/morf/upgrade/TestUpgradeStatusTableServiceImpl.java
Labels: bug

#252 Default methods on ConnectionResources
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/AbstractConnectionResources.java
  morf-core/src/main/java/org/alfasoftware/morf/jdbc/ConnectionResources.java
Labels: bug
